### ISSUE TITLE
Getting comiler error in TestUtils class

### ISSUE THREAD

**Issue by brijesh1100** [spring-cloud/spring-cloud-dataflow#2104]
I have clone and build this repository, while building every thing is working with no error,
but when I am importing the `spring-cloud-dataflow` project I could see the compilation error in TestUtil class.
`spring-cloud-dataflow/spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/TestUtils.java`
```
public static Map<String, String> toImmutableMap(
			String... entries) {
		if(entries.length % 2 == 1)
			throw new IllegalArgumentException("Entries should contain even number of values");
		return Collections.unmodifiableMap(IntStream.range(0, entries.length / 2).map(i -> i * 2)
				.collect(HashMap::new,
						(m, i) -> m.put(entries[i], entries[i + 1]),
						Map::putAll));
	}
```
this method showing error I am using Java8, I am not sure weather it's an issue or not because I am not able to get any build error, but this compilation error is there, so wanted to check, what could be the reason.

![error](https://user-images.githubusercontent.com/14902544/37344174-a9f1578a-26ef-11e8-8530-556ac7ee518c.png)

**Comment by garyrussell** [comment]
You probably need to upgrade your STS/Eclipse version; older versions of the JDT compiler had some problems with inferring generic types. 

It works fine in STS 3.9.1/Eclipse Oxygen 4.7.1a:

![screen shot 2018-03-13 at 11 30 33 am](https://user-images.githubusercontent.com/483832/37351764-2ba94be0-26b2-11e8-8fc7-d97cdf7d0458.png)

**Comment by brijesh1100** [comment]
Thanks @garyrussell
